# -*- coding: utf-8 -*-
"""disney_package.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TgBcvV4sc3-VVLg8sK-mU_DoXLsAVly6
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib as plt
import csv
from csv import writer #allows us to add rows in csv file
from io import StringIO
from pandas import *
from array import *
# %matplotlib inline

class col:
  def __init__(self,colTitle,csv):
    self.colTitle = colTitle
    ndf = pd.read_csv(csv)

  def colAdd(csv, val):
    ndf[csv.colTitle] =val
    ndf.to_csv(csv, index=False)


try:
  def splitCSV_rate(csv):
      import pandas as pd
      df = pd.read_csv(csv)
      Gdf = df.loc[df['mpaa_rating'] == 'G']
      Gdf.to_csv('DisneyG_rated.csv', index=False)

      PGdf = df.loc[df['mpaa_rating'] == 'PG']
      PGdf.to_csv('DisneyPG_rated.csv', index=False)

      PG13df = df.loc[df['mpaa_rating'] == 'PG-13']
      PG13df.to_csv('DisneyPG13_rated.csv', index=False)

      Rdf = df.loc[df['mpaa_rating'] == 'R']
      Rdf.to_csv('DisneyR_rated.csv', index=False)
except:
  print("file Does not Exist")


def compareSortRate(csv1):
    import pandas as pd
    df = pd.read_csv(csv1) #reads the select csv file

    Gdf = df.loc[df['mpaa_rating'] == 'G']
    PGdf = df.loc[df['mpaa_rating'] == 'PG']
    PG13df = df.loc[df['mpaa_rating'] == 'PG-13']
    Rdf = df.loc[df['mpaa_rating'] == 'R']
  
    sum1 = Gdf['inflation_adjusted_gross'].sum()
    sum2 = PGdf['inflation_adjusted_gross'].sum()
    sum3 = PG13df['inflation_adjusted_gross'].sum()
    sum4 = Rdf['inflation_adjusted_gross'].sum()

    if sum1 > sum2 & sum3 & sum4:
      SGdf = Gdf.sort_values(by=['inflation_adjusted_gross'], ascending=False)
      SGdf.to_csv('DisneyG_rated.csv', index=False)
      print(SGdf)
      print(sum1)
    elif sum2 > sum1 & sum3 & sum4:
      SPGdf = PGdf.sort_values(by=['inflation_adjusted_gross'], ascending=False)
      SPGdf.to_csv('DisneyPG_rated.csv', index=False)
      print(SPGdf)
      print(sum2)
    elif sum3 > sum1 & sum2 & sum4:
      SPG13df = PG13df.sort_values(by=['inflation_adjusted_gross'], ascending=False)
      SPG13df.to_csv('DisneyPG_rated.csv', index=False)
      print(SPG13df)
      print(sum3)
    elif sum4 > sum1 & sum2 & sum3:
      SPG13df = PG13df.sort_values(by=['inflation_adjusted_gross'], ascending=False)
      SPG13df.to_csv('DisneyPG_rated.csv', index=False)
      print(SPG13df)
      print(sum3)
 
    


      



